"""
Seoul Records Production OS — UnitedMasters Distribution Package (v0.1.1)
"""
from __future__ import annotations

import csv
import io
import json
import shutil
import zipfile
from datetime import datetime, timezone
from pathlib import Path

from app.models import ProjectManifest, TrackManifest
from app.project_manager import save_manifest, log_action
from app.state_machine import ProjectStatus
from agents.qc_agent import qc_distribution
from app.config import ALLOW_MP3_FOR_DISTRIBUTION


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


RIGHTS_STATEMENTS = {
    "ai_rights": (
        "This recording was created with AI-assisted music generation tools. "
        "All commercial rights are claimed by Seoul Records. "
        "No third-party artist voice clones were used."
    ),
    "artwork_rights": (
        "All artwork was generated with AI image generation tools. "
        "No licensed third-party artwork, stock imagery, or copyrighted visual elements were used."
    ),
    "no_samples": (
        "This recording contains no third-party samples, interpolations, "
        "or copyrighted musical works. "
        "All melodies, harmonies, and arrangements were generated by AI systems."
    ),
    "no_voice_clone": (
        "No real artist voice cloning technology was used in this recording. "
        "All vocal synthesis is original AI-generated content."
    ),
}


def _find_dsp_cover(output_folder: Path) -> Path | None:
    """
    Locate the DSP cover from step 2.
    Prefers .jpg then .png.
    """
    cover_dir = output_folder / "02_thumbnail_cover" / "final"
    for name in ["dsp_cover_3000x3000.jpg", "dsp_cover_3000x3000.png"]:
        candidate = cover_dir / name
        if candidate.exists():
            return candidate
    return None


def export_distribution_package(
    manifest: ProjectManifest,
    output_folder: Path,
) -> tuple[Path | None, list[str]]:
    """
    Build UnitedMasters-ready distribution package.

    Fix 5: copies DSP cover into unitedmasters/cover/ and includes it in ZIP.
           Sets manifest.distribution.cover_ready = True when cover is present.

    Returns (zip_path, warnings). zip_path is None if blocked.
    """
    dist_root = output_folder / "05_music_distribution" / "unitedmasters"
    audio_dir  = dist_root / "audio"
    cover_dir  = dist_root / "cover"
    meta_dir   = dist_root / "metadata"
    rights_dir = dist_root / "rights"

    for d in [audio_dir, cover_dir, meta_dir, rights_dir]:
        d.mkdir(parents=True, exist_ok=True)

    approved = manifest.approved_tracks()
    # QC will run AFTER all artifacts are generated (F5 warning-order fix)
    warnings: list[str] = []

    # ── MP3-block check ───────────────────────────────────────────────────────
    mp3_only = [t for t in approved if not t.is_wav]
    if mp3_only and not ALLOW_MP3_FOR_DISTRIBUTION:
        manifest.distribution.blocked_reason = (
            f"Distribution blocked: {len(mp3_only)} track(s) have no WAV master. "
            "MP3-to-WAV conversion is not allowed as distribution master."
        )
        save_manifest(manifest, output_folder)
        log_action(
            output_folder, "distribution", "blocked_mp3_only",
            {"mp3_tracks": [t.track_id for t in mp3_only]},
            level="WARNING", project_id=manifest.project_id,
        )
        return None, warnings

    wav_tracks = [t for t in approved if t.is_wav]
    if not wav_tracks:
        manifest.distribution.blocked_reason = "Distribution blocked: no WAV masters found."
        save_manifest(manifest, output_folder)
        return None, warnings

    # ── Copy WAV masters ──────────────────────────────────────────────────────
    track_metadata_rows: list[dict] = []
    for t in wav_tracks:
        src = Path(t.selected_wav_path)
        if not src.exists():
            warnings.append(f"wav_missing_for_track_{t.track_number}")
            continue
        safe_title = (t.prompt.title or f"track_{t.track_number}") \
            .replace(" ", "_").replace("/", "-")[:40]
        dest_name = f"{t.track_number:02d}_{safe_title}.wav"
        shutil.copy2(src, audio_dir / dest_name)
        track_metadata_rows.append({
            "track_number": t.track_number,
            "title": t.prompt.title or "",
            "duration_seconds": t.duration_seconds or "",
            "file": dest_name,
            "is_wav": True,
            "distribution_eligible": t.distribution_eligible,
        })

    # ── Fix 5: Copy DSP cover into unitedmasters/cover/ ──────────────────────
    cover_src = _find_dsp_cover(output_folder)
    cover_copied = False
    if cover_src:
        dest_cover = cover_dir / f"unitedmasters_cover_3000x3000{cover_src.suffix}"
        shutil.copy2(cover_src, dest_cover)
        cover_copied = True
        manifest.distribution.cover_ready = True
        # Remove stale cover_not_ready warning if present
        warnings = [w for w in warnings if w != "cover_not_ready"]
    else:
        warnings.append("dsp_cover_source_missing_generate_in_tab2")

    # ── Release metadata (JSON) ───────────────────────────────────────────────
    release_meta = {
        "project_name": manifest.project_name,
        "project_id": manifest.project_id,
        "core_style": manifest.core_style,
        "language_pack": manifest.language_pack,
        "track_count": len(wav_tracks),
        "label": "Seoul Records",
        "genre": "Pop / City Pop",
        "sub_genre": "Japanese City Pop",
        "cover_included": cover_copied,
        "generated_at": _now(),
        "app_version": manifest.app_version,
    }
    (meta_dir / "release_metadata.json").write_text(
        json.dumps(release_meta, indent=2), encoding="utf-8"
    )

    # ── Fix 8: CSV via csv module — no manual comma concatenation ─────────────
    # release_metadata.csv
    buf = io.StringIO()
    w = csv.writer(buf, quoting=csv.QUOTE_MINIMAL)
    w.writerow(["track_number", "title", "duration_seconds", "file", "is_wav"])
    for row in track_metadata_rows:
        w.writerow([row["track_number"], row["title"],
                    row["duration_seconds"], row["file"], row["is_wav"]])
    (meta_dir / "release_metadata.csv").write_text(buf.getvalue(), encoding="utf-8")

    # track_metadata.csv
    buf2 = io.StringIO()
    w2 = csv.writer(buf2, quoting=csv.QUOTE_MINIMAL)
    w2.writerow(["#", "Title", "Duration", "File", "Eligible"])
    for row in track_metadata_rows:
        w2.writerow([row["track_number"], row["title"],
                     row["duration_seconds"], row["file"],
                     row["distribution_eligible"]])
    (meta_dir / "track_metadata.csv").write_text(buf2.getvalue(), encoding="utf-8")

    # ── Upload checklist ──────────────────────────────────────────────────────
    cover_status = "✅ Included" if cover_copied else "❌ Missing — generate in Tab 2"
    checklist = f"""# Seoul Records — UnitedMasters Upload Checklist

## Project: {manifest.project_name}
Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}

## Pre-Upload Checklist

- [ ] WAV masters verified ({len(wav_tracks)} tracks)
- [ ] Cover art 3000×3000:  {cover_status}
- [ ] Release title set
- [ ] Label: Seoul Records
- [ ] Genre: Pop / City Pop
- [ ] Release date selected
- [ ] Track order confirmed
- [ ] Rights statements reviewed
- [ ] No third-party samples confirmed
- [ ] No voice clones confirmed

## Do NOT Upload
- ❌ MP3 files (WAV only)
- ❌ Converted MP3-to-WAV files
- ❌ Preview exports

## Distribution Rules
- Format: WAV 16-bit 44.1kHz stereo
- Cover: 3000×3000 JPEG, no text, no watermarks
- Do NOT click Submit without final human review
"""
    (meta_dir / "upload_checklist.md").write_text(checklist, encoding="utf-8")

    # ── Rights statements ─────────────────────────────────────────────────────
    (rights_dir / "ai_rights_statement.txt").write_text(
        RIGHTS_STATEMENTS["ai_rights"], encoding="utf-8")
    (rights_dir / "artwork_rights_statement.txt").write_text(
        RIGHTS_STATEMENTS["artwork_rights"], encoding="utf-8")
    (rights_dir / "no_third_party_samples_statement.txt").write_text(
        RIGHTS_STATEMENTS["no_samples"], encoding="utf-8")
    (rights_dir / "no_artist_voice_clone_statement.txt").write_text(
        RIGHTS_STATEMENTS["no_voice_clone"], encoding="utf-8")

    # ── Distribution manifest ─────────────────────────────────────────────────
    dist_manifest = {
        "status": "package_ready",
        "wav_count": len(wav_tracks),
        "cover_included": cover_copied,
        "tracks": track_metadata_rows,
        "rights_included": list(RIGHTS_STATEMENTS.keys()),
        "generated_at": _now(),
    }
    (output_folder / "05_music_distribution" / "distribution_manifest.json").write_text(
        json.dumps(dist_manifest, indent=2), encoding="utf-8"
    )

    # ── ZIP package ───────────────────────────────────────────────────────────
    zip_path = output_folder / "export_package" / "unitedmasters_package.zip"
    zip_path.parent.mkdir(exist_ok=True)
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        # WAV masters
        for file in audio_dir.iterdir():
            if file.is_file():
                zf.write(file, Path("audio") / file.name)
        # Cover art (Fix 5: explicitly include)
        for file in cover_dir.iterdir():
            if file.is_file():
                zf.write(file, Path("cover") / file.name)
        # Metadata
        for file in meta_dir.iterdir():
            if file.is_file():
                zf.write(file, Path("metadata") / file.name)
        # Rights
        for file in rights_dir.iterdir():
            if file.is_file():
                zf.write(file, Path("rights") / file.name)

    # ── F5 Warning Fix: run QC AFTER all artifacts generated ─────────────────
    # metadata_ready and rights_statements_ready are already True at this point,
    # so qc_distribution will not emit false "metadata_not_ready" warnings.
    manifest.distribution.metadata_ready = True
    manifest.distribution.rights_statements_ready = True
    manifest.distribution.cover_ready = cover_copied
    post_qc_warnings = qc_distribution(manifest.distribution, wav_tracks)
    # Merge: keep any block-level warnings from earlier, add post-generation warnings
    for w in post_qc_warnings:
        if w not in warnings:
            warnings.append(w)

    # ── Update manifest ───────────────────────────────────────────────────────
    manifest.distribution.status = "package_ready"
    manifest.distribution.package_path = str(zip_path)
    manifest.distribution.wav_masters_count = len(wav_tracks)
    manifest.distribution.wav_masters_ready = len(wav_tracks) > 0
    manifest.distribution.updated_at = _now()
    manifest.update_status(ProjectStatus.DISTRIBUTION_PACKAGE_READY)
    save_manifest(manifest, output_folder)

    log_action(
        output_folder, "distribution", "package_exported",
        {"zip_path": str(zip_path), "wav_count": len(wav_tracks),
         "cover_included": cover_copied},
        project_id=manifest.project_id,
    )

    return zip_path, warnings
