"""
DistributorAgent — assembles and validates the distribution package.

v0.1: Creates manual export package for UnitedMasters.
v0.6+: Playwright-assisted web upload (stops before final Submit).

RULES:
- WAV required. MP3 is not eligible.
- MP3-to-WAV conversion is NOT allowed as distribution master.
- Use WAV 16-bit 44.1kHz stereo.
- Block distribution if WAV master is missing.
- Always stop before clicking Submit in Playwright mode.
"""

from __future__ import annotations
import os
import json
import csv
import shutil
from datetime import datetime, timezone
from typing import Optional


class DistributorAgent:
    """Validates and assembles the UnitedMasters distribution package."""

    def __init__(self, project_dir: str):
        self.project_dir = project_dir
        self.dist_dir = os.path.join(project_dir, "05_music_distribution", "unitedmasters")

    # ------------------------------------------------------------------
    # Eligibility checks
    # ------------------------------------------------------------------

    def check_track_eligibility(self, track: dict) -> tuple[bool, str]:
        """
        Returns (eligible, reason).
        Blocks if WAV master is missing or only MP3 exists.
        """
        wav_path = track.get("wav_path") or track.get("master_wav_path")
        mp3_path = track.get("mp3_path") or track.get("preview_mp3_path")

        if not wav_path or not os.path.exists(wav_path):
            if mp3_path and os.path.exists(mp3_path):
                return False, "BLOCKED: Only MP3 exists. MP3-to-WAV conversion is not allowed."
            return False, "BLOCKED: WAV master is missing."
        return True, "eligible"

    def check_cover_eligibility(self, cover_path: Optional[str]) -> tuple[bool, str]:
        """Checks that 1:1 cover exists and is a valid image."""
        if not cover_path or not os.path.exists(cover_path):
            return False, "BLOCKED: DSP cover (1:1) is missing."
        # Dimension check via PIL if available
        try:
            from PIL import Image
            with Image.open(cover_path) as img:
                w, h = img.size
                if w != h:
                    return False, f"BLOCKED: Cover is not square ({w}x{h})."
                if w < 3000:
                    return False, f"BLOCKED: Cover is too small ({w}x{h}). Need 3000x3000."
        except ImportError:
            pass  # PIL not available; skip dimension check
        return True, "eligible"

    # ------------------------------------------------------------------
    # Package assembly
    # ------------------------------------------------------------------

    def build_rights_statements(self, output_dir: str) -> None:
        """Write the four required rights statement files."""
        rights_dir = os.path.join(output_dir, "rights")
        os.makedirs(rights_dir, exist_ok=True)

        statements = {
            "ai_rights_statement.txt": (
                "AI-Generated Music Rights Statement\n"
                "=====================================\n"
                "This track was created using AI music generation tools.\n"
                "The rights to this recording are claimed by Seoul Records.\n"
                "The AI-generated audio does not contain samples from or replicas\n"
                "of any human artist's voice without explicit license.\n"
            ),
            "artwork_rights_statement.txt": (
                "Artwork Rights Statement\n"
                "========================\n"
                "The cover artwork was generated using AI image generation tools.\n"
                "The artwork does not reproduce any copyrighted images, brand logos,\n"
                "or identifiable likenesses of real persons.\n"
                "Rights to the artwork are claimed by Seoul Records.\n"
            ),
            "no_third_party_samples_statement.txt": (
                "No Third-Party Samples Statement\n"
                "=================================\n"
                "This recording contains no samples from third-party recordings.\n"
                "All musical elements were generated by AI.\n"
                "No sample clearance is required.\n"
            ),
            "no_artist_voice_clone_statement.txt": (
                "No Artist Voice Clone Statement\n"
                "================================\n"
                "This recording does not use a voice clone of any real human artist.\n"
                "The vocal performance was generated by AI without replicating\n"
                "any specific individual's voice.\n"
            ),
        }

        for filename, content in statements.items():
            with open(os.path.join(rights_dir, filename), "w", encoding="utf-8") as f:
                f.write(content)

    def assemble_package(
        self,
        tracks: list[dict],
        cover_path: Optional[str],
        release_metadata: dict,
    ) -> dict:
        """
        Assemble the full UnitedMasters distribution package.

        Returns result dict with status, blocked_tracks, package_path.
        """
        audio_dir = os.path.join(self.dist_dir, "audio")
        cover_dir = os.path.join(self.dist_dir, "cover")
        metadata_dir = os.path.join(self.dist_dir, "metadata")
        rights_dir = os.path.join(self.dist_dir, "rights")

        for d in [audio_dir, cover_dir, metadata_dir, rights_dir]:
            os.makedirs(d, exist_ok=True)

        blocked = []
        copied = []

        # Audio masters
        for i, track in enumerate(tracks, 1):
            eligible, reason = self.check_track_eligibility(track)
            if not eligible:
                blocked.append({"track": track.get("title", f"track_{i}"), "reason": reason})
                continue
            wav_src = track["wav_path"]
            safe_title = track.get("title", f"track_{i:02d}").replace(" ", "_")
            dest = os.path.join(audio_dir, f"{i:02d}_{safe_title}.wav")
            shutil.copy2(wav_src, dest)
            copied.append({"track": track.get("title"), "dest": dest})

        # Cover art
        cover_status = "missing"
        if cover_path:
            cover_eligible, cover_reason = self.check_cover_eligibility(cover_path)
            if cover_eligible:
                dest_cover = os.path.join(cover_dir, "unitedmasters_cover_3000x3000.jpg")
                shutil.copy2(cover_path, dest_cover)
                cover_status = "ok"
            else:
                blocked.append({"track": "cover", "reason": cover_reason})

        # Release metadata
        release_metadata["generated_at"] = datetime.now(timezone.utc).isoformat()
        with open(os.path.join(metadata_dir, "release_metadata.json"), "w") as f:
            json.dump(release_metadata, f, indent=2, ensure_ascii=False)

        # CSV exports
        self._write_release_csv(release_metadata, metadata_dir)
        self._write_track_csv(tracks, metadata_dir)
        self._write_checklist(tracks, metadata_dir, blocked)

        # Rights statements
        self.build_rights_statements(self.dist_dir)

        # Distribution manifest
        manifest = {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "tracks_total": len(tracks),
            "tracks_eligible": len(copied),
            "tracks_blocked": len(blocked),
            "cover_status": cover_status,
            "blocked_details": blocked,
        }
        with open(os.path.join(self.dist_dir, "..", "distribution_manifest.json"), "w") as f:
            json.dump(manifest, f, indent=2, ensure_ascii=False)

        return {
            "status": "blocked" if blocked else "ready",
            "blocked_tracks": blocked,
            "eligible_tracks": copied,
            "package_dir": self.dist_dir,
        }

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _write_release_csv(self, metadata: dict, output_dir: str) -> None:
        path = os.path.join(output_dir, "release_metadata.csv")
        with open(path, "w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            for k, v in metadata.items():
                writer.writerow([k, v])

    def _write_track_csv(self, tracks: list[dict], output_dir: str) -> None:
        path = os.path.join(output_dir, "track_metadata.csv")
        if not tracks:
            return
        keys = list(tracks[0].keys())
        with open(path, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=keys, extrasaction="ignore")
            writer.writeheader()
            writer.writerows(tracks)

    def _write_checklist(self, tracks: list[dict], output_dir: str, blocked: list) -> None:
        path = os.path.join(output_dir, "upload_checklist.md")
        lines = [
            "# UnitedMasters Upload Checklist\n",
            f"Generated: {datetime.now(timezone.utc).isoformat()}\n\n",
            "## Pre-Upload Checks\n",
            "- [ ] WAV masters (16-bit 44.1kHz stereo) present in audio/\n",
            "- [ ] Cover art (3000×3000 JPG) present in cover/\n",
            "- [ ] release_metadata.json complete\n",
            "- [ ] track_metadata.csv complete\n",
            "- [ ] Rights statements signed off\n",
            "- [ ] No MP3-only tracks\n\n",
            "## Track Status\n",
        ]
        for i, track in enumerate(tracks, 1):
            title = track.get("title", f"Track {i}")
            is_blocked = any(b["track"] == title for b in blocked)
            status = "❌ BLOCKED" if is_blocked else "✅ Ready"
            lines.append(f"- {i:02d}. {title} — {status}\n")

        if blocked:
            lines.append("\n## Blocked Details\n")
            for b in blocked:
                lines.append(f"- **{b['track']}**: {b['reason']}\n")

        with open(path, "w", encoding="utf-8") as f:
            f.writelines(lines)
